//! Fixed-size vectors: [`Vec2`], [`Vec3`], [`Vec4`].
//!
//! All components are `f64` (crate convention). The three types are written
//! out longhand rather than generated by a macro so each operation stays
//! readable — the repetition is the point, not an accident to refactor away.
//!
//! Every operation takes `self` by value: these types are small `Copy`
//! structs, and by-value math is what makes `a + b * 2.0` read like algebra.

use std::ops::{Add, Div, Mul, Neg, Sub};

use crate::EPSILON;

/// Absolute-difference comparison for `f64` in tests.
///
/// Floating-point results accumulate rounding error, so tests must never use
/// `==` except for identities that are exact (e.g. multiplying by an exact
/// identity matrix). `1e-9` is loose enough for chained f64 ops and tight
/// enough to catch real bugs.
#[cfg(test)]
pub(crate) fn approx_eq(a: f64, b: f64) -> bool {
    (a - b).abs() < 1e-9
}

/// A 2D vector.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Vec2 {
    /// X component.
    pub x: f64,
    /// Y component.
    pub y: f64,
}

impl Vec2 {
    /// The zero vector.
    pub const ZERO: Self = Self { x: 0.0, y: 0.0 };
    /// The all-ones vector.
    pub const ONE: Self = Self { x: 1.0, y: 1.0 };

    /// Create a vector from components.
    pub fn new(x: f64, y: f64) -> Self {
        Self { x, y }
    }

    /// Dot product: `|a||b|cos(angle)`; zero when perpendicular.
    pub fn dot(self, rhs: Self) -> f64 {
        self.x * rhs.x + self.y * rhs.y
    }

    /// Squared Euclidean length. Cheaper than [`Self::length`] (no square
    /// root) — prefer it for comparisons.
    pub fn length_squared(self) -> f64 {
        self.dot(self)
    }

    /// Euclidean length (magnitude).
    pub fn length(self) -> f64 {
        self.length_squared().sqrt()
    }

    /// Return the unit-length vector pointing the same way, or `None` if the
    /// length is below [`EPSILON`] (a near-zero vector has no direction).
    pub fn normalize(self) -> Option<Self> {
        let len = self.length();
        if len < EPSILON {
            None
        } else {
            Some(self / len)
        }
    }

    /// Linear interpolation: `t = 0` gives `self`, `t = 1` gives `rhs`.
    /// Values outside `[0, 1]` extrapolate.
    pub fn lerp(self, rhs: Self, t: f64) -> Self {
        self + (rhs - self) * t
    }
}

impl Add for Vec2 {
    type Output = Self;
    fn add(self, rhs: Self) -> Self {
        Self::new(self.x + rhs.x, self.y + rhs.y)
    }
}

impl Sub for Vec2 {
    type Output = Self;
    fn sub(self, rhs: Self) -> Self {
        Self::new(self.x - rhs.x, self.y - rhs.y)
    }
}

impl Neg for Vec2 {
    type Output = Self;
    fn neg(self) -> Self {
        Self::new(-self.x, -self.y)
    }
}

impl Mul<f64> for Vec2 {
    type Output = Self;
    fn mul(self, s: f64) -> Self {
        Self::new(self.x * s, self.y * s)
    }
}

impl Div<f64> for Vec2 {
    type Output = Self;
    fn div(self, s: f64) -> Self {
        Self::new(self.x / s, self.y / s)
    }
}

/// A 3D vector — the workhorse type for positions, directions, and scales.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Vec3 {
    /// X component.
    pub x: f64,
    /// Y component.
    pub y: f64,
    /// Z component.
    pub z: f64,
}

impl Vec3 {
    /// The zero vector.
    pub const ZERO: Self = Self {
        x: 0.0,
        y: 0.0,
        z: 0.0,
    };
    /// The all-ones vector (e.g. an identity scale).
    pub const ONE: Self = Self {
        x: 1.0,
        y: 1.0,
        z: 1.0,
    };
    /// Unit vector along +X (right, in the crate's right-handed frame).
    pub const X: Self = Self {
        x: 1.0,
        y: 0.0,
        z: 0.0,
    };
    /// Unit vector along +Y (up).
    pub const Y: Self = Self {
        x: 0.0,
        y: 1.0,
        z: 0.0,
    };
    /// Unit vector along +Z (towards the viewer; cameras look down −Z).
    pub const Z: Self = Self {
        x: 0.0,
        y: 0.0,
        z: 1.0,
    };

    /// Create a vector from components.
    pub fn new(x: f64, y: f64, z: f64) -> Self {
        Self { x, y, z }
    }

    /// Dot product: `|a||b|cos(angle)`; zero when perpendicular.
    pub fn dot(self, rhs: Self) -> f64 {
        self.x * rhs.x + self.y * rhs.y + self.z * rhs.z
    }

    /// Cross product: a vector perpendicular to both operands, oriented by
    /// the **right-hand rule** (`X.cross(Y) == Z`), with length
    /// `|a||b|sin(angle)`. Anti-commutative: `a.cross(b) == -(b.cross(a))`.
    pub fn cross(self, rhs: Self) -> Self {
        Self::new(
            self.y * rhs.z - self.z * rhs.y,
            self.z * rhs.x - self.x * rhs.z,
            self.x * rhs.y - self.y * rhs.x,
        )
    }

    /// Squared Euclidean length. Cheaper than [`Self::length`] (no square
    /// root) — prefer it for comparisons.
    pub fn length_squared(self) -> f64 {
        self.dot(self)
    }

    /// Euclidean length (magnitude).
    pub fn length(self) -> f64 {
        self.length_squared().sqrt()
    }

    /// Return the unit-length vector pointing the same way, or `None` if the
    /// length is below [`EPSILON`] (a near-zero vector has no direction).
    pub fn normalize(self) -> Option<Self> {
        let len = self.length();
        if len < EPSILON {
            None
        } else {
            Some(self / len)
        }
    }

    /// Linear interpolation: `t = 0` gives `self`, `t = 1` gives `rhs`.
    /// Values outside `[0, 1]` extrapolate.
    pub fn lerp(self, rhs: Self, t: f64) -> Self {
        self + (rhs - self) * t
    }
}

impl Add for Vec3 {
    type Output = Self;
    fn add(self, rhs: Self) -> Self {
        Self::new(self.x + rhs.x, self.y + rhs.y, self.z + rhs.z)
    }
}

impl Sub for Vec3 {
    type Output = Self;
    fn sub(self, rhs: Self) -> Self {
        Self::new(self.x - rhs.x, self.y - rhs.y, self.z - rhs.z)
    }
}

impl Neg for Vec3 {
    type Output = Self;
    fn neg(self) -> Self {
        Self::new(-self.x, -self.y, -self.z)
    }
}

impl Mul<f64> for Vec3 {
    type Output = Self;
    fn mul(self, s: f64) -> Self {
        Self::new(self.x * s, self.y * s, self.z * s)
    }
}

impl Div<f64> for Vec3 {
    type Output = Self;
    fn div(self, s: f64) -> Self {
        Self::new(self.x / s, self.y / s, self.z / s)
    }
}

/// A 4D vector — a 3D point (`w = 1`) or direction (`w = 0`) in the
/// homogeneous coordinates that [`crate::Mat4`] operates on.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Vec4 {
    /// X component.
    pub x: f64,
    /// Y component.
    pub y: f64,
    /// Z component.
    pub z: f64,
    /// W component (the homogeneous coordinate).
    pub w: f64,
}

impl Vec4 {
    /// The zero vector.
    pub const ZERO: Self = Self {
        x: 0.0,
        y: 0.0,
        z: 0.0,
        w: 0.0,
    };
    /// The all-ones vector.
    pub const ONE: Self = Self {
        x: 1.0,
        y: 1.0,
        z: 1.0,
        w: 1.0,
    };

    /// Create a vector from components.
    pub fn new(x: f64, y: f64, z: f64, w: f64) -> Self {
        Self { x, y, z, w }
    }

    /// Dot product: `|a||b|cos(angle)`; zero when perpendicular.
    pub fn dot(self, rhs: Self) -> f64 {
        self.x * rhs.x + self.y * rhs.y + self.z * rhs.z + self.w * rhs.w
    }

    /// Squared Euclidean length. Cheaper than [`Self::length`] (no square
    /// root) — prefer it for comparisons.
    pub fn length_squared(self) -> f64 {
        self.dot(self)
    }

    /// Euclidean length (magnitude).
    pub fn length(self) -> f64 {
        self.length_squared().sqrt()
    }

    /// Return the unit-length vector pointing the same way, or `None` if the
    /// length is below [`EPSILON`] (a near-zero vector has no direction).
    pub fn normalize(self) -> Option<Self> {
        let len = self.length();
        if len < EPSILON {
            None
        } else {
            Some(self / len)
        }
    }

    /// Linear interpolation: `t = 0` gives `self`, `t = 1` gives `rhs`.
    /// Values outside `[0, 1]` extrapolate.
    pub fn lerp(self, rhs: Self, t: f64) -> Self {
        self + (rhs - self) * t
    }
}

impl Add for Vec4 {
    type Output = Self;
    fn add(self, rhs: Self) -> Self {
        Self::new(
            self.x + rhs.x,
            self.y + rhs.y,
            self.z + rhs.z,
            self.w + rhs.w,
        )
    }
}

impl Sub for Vec4 {
    type Output = Self;
    fn sub(self, rhs: Self) -> Self {
        Self::new(
            self.x - rhs.x,
            self.y - rhs.y,
            self.z - rhs.z,
            self.w - rhs.w,
        )
    }
}

impl Neg for Vec4 {
    type Output = Self;
    fn neg(self) -> Self {
        Self::new(-self.x, -self.y, -self.z, -self.w)
    }
}

impl Mul<f64> for Vec4 {
    type Output = Self;
    fn mul(self, s: f64) -> Self {
        Self::new(self.x * s, self.y * s, self.z * s, self.w * s)
    }
}

impl Div<f64> for Vec4 {
    type Output = Self;
    fn div(self, s: f64) -> Self {
        Self::new(self.x / s, self.y / s, self.z / s, self.w / s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v3_approx_eq(a: Vec3, b: Vec3) -> bool {
        approx_eq(a.x, b.x) && approx_eq(a.y, b.y) && approx_eq(a.z, b.z)
    }

    #[test]
    fn vec2_arithmetic() {
        let a = Vec2::new(1.0, 2.0);
        let b = Vec2::new(3.0, -4.0);
        assert_eq!(a + b, Vec2::new(4.0, -2.0));
        assert_eq!(a - b, Vec2::new(-2.0, 6.0));
        assert_eq!(-a, Vec2::new(-1.0, -2.0));
        assert_eq!(a * 2.0, Vec2::new(2.0, 4.0));
        assert_eq!(b / 2.0, Vec2::new(1.5, -2.0));
    }

    #[test]
    fn vec2_dot_length_lerp() {
        let a = Vec2::new(3.0, 4.0);
        assert!(approx_eq(a.dot(Vec2::new(1.0, 1.0)), 7.0));
        assert!(approx_eq(a.length_squared(), 25.0));
        assert!(approx_eq(a.length(), 5.0));
        let mid = Vec2::ZERO.lerp(Vec2::ONE, 0.5);
        assert!(approx_eq(mid.x, 0.5) && approx_eq(mid.y, 0.5));
    }

    #[test]
    fn vec2_normalize() {
        let n = Vec2::new(3.0, 4.0).normalize().unwrap();
        assert!(approx_eq(n.length(), 1.0));
        assert!(approx_eq(n.x, 0.6) && approx_eq(n.y, 0.8));
        assert!(Vec2::ZERO.normalize().is_none());
    }

    #[test]
    fn vec3_arithmetic() {
        let a = Vec3::new(1.0, 2.0, 3.0);
        let b = Vec3::new(-1.0, 0.5, 2.0);
        assert_eq!(a + b, Vec3::new(0.0, 2.5, 5.0));
        assert_eq!(a - b, Vec3::new(2.0, 1.5, 1.0));
        assert_eq!(-a, Vec3::new(-1.0, -2.0, -3.0));
        assert_eq!(a * 3.0, Vec3::new(3.0, 6.0, 9.0));
        assert_eq!(a / 2.0, Vec3::new(0.5, 1.0, 1.5));
    }

    #[test]
    fn vec3_dot_perpendicular_is_zero() {
        assert!(approx_eq(Vec3::X.dot(Vec3::Y), 0.0));
        let a = Vec3::new(1.0, 2.0, 3.0);
        assert!(approx_eq(a.dot(a), a.length_squared()));
    }

    #[test]
    fn vec3_cross_right_hand_rule() {
        // The defining property of the right-handed frame: X × Y = Z, and
        // cyclic permutations.
        assert!(v3_approx_eq(Vec3::X.cross(Vec3::Y), Vec3::Z));
        assert!(v3_approx_eq(Vec3::Y.cross(Vec3::Z), Vec3::X));
        assert!(v3_approx_eq(Vec3::Z.cross(Vec3::X), Vec3::Y));
        // Anti-commutative.
        assert!(v3_approx_eq(Vec3::Y.cross(Vec3::X), -Vec3::Z));
        // Parallel vectors have a zero cross product.
        let a = Vec3::new(2.0, -1.0, 4.0);
        assert!(approx_eq(a.cross(a * 3.0).length(), 0.0));
        // Result is perpendicular to both inputs.
        let b = Vec3::new(0.5, 3.0, -2.0);
        let c = a.cross(b);
        assert!(approx_eq(c.dot(a), 0.0) && approx_eq(c.dot(b), 0.0));
    }

    #[test]
    fn vec3_normalize() {
        let n = Vec3::new(1.0, 2.0, -2.0).normalize().unwrap();
        assert!(approx_eq(n.length(), 1.0));
        assert!(v3_approx_eq(n, Vec3::new(1.0, 2.0, -2.0) / 3.0));
        assert!(Vec3::ZERO.normalize().is_none());
        // Just below the epsilon threshold also fails.
        assert!(Vec3::new(1e-13, 0.0, 0.0).normalize().is_none());
    }

    #[test]
    fn vec3_lerp_endpoints_and_midpoint() {
        let a = Vec3::new(1.0, 2.0, 3.0);
        let b = Vec3::new(5.0, -2.0, 7.0);
        assert!(v3_approx_eq(a.lerp(b, 0.0), a));
        assert!(v3_approx_eq(a.lerp(b, 1.0), b));
        assert!(v3_approx_eq(a.lerp(b, 0.5), Vec3::new(3.0, 0.0, 5.0)));
    }

    #[test]
    fn vec4_arithmetic() {
        let a = Vec4::new(1.0, 2.0, 3.0, 4.0);
        let b = Vec4::new(4.0, 3.0, 2.0, 1.0);
        assert_eq!(a + b, Vec4::new(5.0, 5.0, 5.0, 5.0));
        assert_eq!(a - b, Vec4::new(-3.0, -1.0, 1.0, 3.0));
        assert_eq!(-a, Vec4::new(-1.0, -2.0, -3.0, -4.0));
        assert_eq!(a * 2.0, Vec4::new(2.0, 4.0, 6.0, 8.0));
        assert_eq!(a / 4.0, Vec4::new(0.25, 0.5, 0.75, 1.0));
        assert!(approx_eq(a.dot(b), 20.0));
    }

    #[test]
    fn vec4_length_normalize_lerp() {
        let a = Vec4::new(2.0, 0.0, 0.0, 0.0);
        assert!(approx_eq(a.length_squared(), 4.0));
        assert!(approx_eq(a.length(), 2.0));
        let n = a.normalize().unwrap();
        assert!(approx_eq(n.length(), 1.0));
        assert!(Vec4::ZERO.normalize().is_none());
        let mid = Vec4::ZERO.lerp(Vec4::ONE, 0.5);
        assert!(approx_eq(mid.x, 0.5) && approx_eq(mid.w, 0.5));
    }

    #[test]
    fn defaults_are_zero() {
        assert_eq!(Vec2::default(), Vec2::ZERO);
        assert_eq!(Vec3::default(), Vec3::ZERO);
        assert_eq!(Vec4::default(), Vec4::ZERO);
    }
}
